apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  otel-collector-config.yaml: |
    receivers: 
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            
    processors:
      batch:
        timeout: 5s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128
      resource:
        attributes:
          - key: k8s.cluster.name
            value: minikube
            action: upsert
      
    exporters:
      prometheusremotewrite:
        endpoint: http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write
        tls:
          insecure: true
          
      otlp/tempo:
        endpoint: http://tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
          
      otlphttp/loki:
        endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
        tls:
          insecure: true
            
      debug:
        verbosity: detailed
        
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      extensions:  [health_check, zpages]
      pipelines:
        traces:
          receivers:  [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [otlp/tempo]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [otlphttp/loki]
      telemetry:
        logs:
          level: info
