# Chart - grafana/tempo

tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

  readinessProbe:
    httpGet:
      path: /ready
      port: 3200
      scheme: HTTP
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 15
    failureThreshold: 3

  livenessProbe:
    httpGet:
      path: /ready
      port: 3200
      scheme: HTTP
    initialDelaySeconds: 90
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 5

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "300m"

persistence:
  enabled: true
  size: 2Gi
  storageClassName: standard

tempoQuery:
  enabled: true